/*
This class switches to ResultFrag when clicked and passes along answer chosen
 */
package com.jdporras.assignment2;

import android.graphics.Color;
import android.os.Bundle;

import androidx.fragment.app.Fragment;
import androidx.fragment.app.FragmentManager;
import androidx.fragment.app.FragmentTransaction;

import android.util.Log;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.Button;

/**
 * A simple {@link Fragment} subclass.
 * Use the {@link AnswerFrag#newInstance} factory method to
 * create an instance of this fragment.
 */

/*
    Most of the top half of this fragment as well as ResultsFrag was generated by the compiler and I'm not entirely sure if it's necessary,
    but I kept it just to be safe
 */

public class AnswerFrag extends Fragment{
    Button answer;
    // the fragment initialization parameters, e.g. ARG_ITEM_NUMBER
    private static final String ARG_PARAM1 = "param1";
    private static final String ARG_PARAM2 = "param2";

    private String mParam1;
    private String mParam2;

    public AnswerFrag() {
        // Required empty public constructor
    }

    /**
     * Use this factory method to create a new instance of
     * this fragment using the provided parameters.
     *
     * @param param1 Parameter 1.
     * @param param2 Parameter 2.
     * @return A new instance of fragment AnswerFrag.
     */
    public static AnswerFrag newInstance(String param1, String param2) {
        AnswerFrag fragment = new AnswerFrag();
        Bundle args = new Bundle();
        args.putString(ARG_PARAM1, param1);
        args.putString(ARG_PARAM2, param2);
        fragment.setArguments(args);
        return fragment;
    }

    @Override
    public void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        if (getArguments() != null) {
            mParam1 = getArguments().getString(ARG_PARAM1);
            mParam2 = getArguments().getString(ARG_PARAM2);
        }
    }

    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container,
                             Bundle savedInstanceState) {
        View view = inflater.inflate(R.layout.fragment_answer, container, false);
        answer = view.findViewById(R.id.answer);
        answer.setOnClickListener(new View.OnClickListener() {
            @Override
            //this clickListener sets proper values according to whether the selected answer was correct or not
            public void onClick(View v) {
                if(SecondaryActivity.ResultsHolder.getAns() == SecondaryActivity.ResultsHolder.getCorrect()){
                    SecondaryActivity.ResultsHolder.setIsCorrect(true);
                    SecondaryActivity.ResultsHolder.incCorrectCounter();
                }
                else{
                    SecondaryActivity.ResultsHolder.setIsCorrect(false);
                }
                //this section transitions the Answer fragment to the result fragment
                ResultFrag result = new ResultFrag();
                FragmentTransaction trans = getFragmentManager().beginTransaction();
                trans.replace(R.id.flfragment, result);
                trans.commit();
            }
        });
        // Inflate the layout for this fragment
        return view;
    }
}